### ISSUE TITLE
Shared folder for downloaded image

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/skin-crawler#11]
Since two of our API sources (Kaggle and ISIC) require downloading to the backend, let's move those images to a common folder `backend/images/` for ease of hosting. They should be named in a way to avoid conflict (e.g. prefixing with ISIC- and Kaggle-). As far as I'm aware ISIC images are already prefixed, not sure about Kaggle.

**Comment by Huy-Ngo** [comment]
I will link those in the route /images manually then.

**Comment by Huy-Ngo** [comment]
Reopen this issue.

I just learned that files in the `./static/` are served automatically by flask where `.` is the same directory as `app.py`. Please move the downloaded images folder to `backend/static/isic/` and `backend/static/kaggle/` @dinhanhx @casker2209 

Like this:

![image](https://user-images.githubusercontent.com/19296926/99867098-2438ab00-2be9-11eb-8d1c-30c44951fddc.png)

**Comment by Huy-Ngo** [comment]
If possible, please move the config file inside the project folder as well @dinhanhx

**Comment by dinhanhx** [comment]
> If possible, please move the config file inside the project folder as well @dinhanhx

The kaggle api token file's path is fixed and defined by module [kaggle-api](https://github.com/Kaggle/kaggle-api#api-credentials). Therefore it's not possible for me to move it into project folder.

**Comment by Huy-Ngo** [comment]
OK then. Until this issue is resolved, I'll finish my PR as it it already has been.

**Comment by dinhanhx** [comment]
> I just learned that files in the `./static/` are served automatically by flask where `.` is the same directory as `app.py`. Please move the downloaded images folder to `backend/static/isic/` and `backend/static/kaggle/` @dinhanhx @casker2209

According to my own [kaggle doc download func](https://github.com/Huy-Ngo/skin-crawler/tree/main/backend/kaggle#download-a-dataset), you can specify download path by yourself.

For example, I assume you have this block of code in [`app.py`](https://github.com/Huy-Ngo/skin-crawler/blob/main/backend/app.py),
```Python
from pathlib import Path
import kaggle

download_path = './static/kaggle/'
download_path = Path(download_path)
dataset_path = kaggle.download('dinhanhx/skin-cancer-mnist-ham10000', download_path)
scm = kaggle.SkinCancerMnist(dataset_path)
```

**Comment by Huy-Ngo** [comment]
Oh I see.
