### ISSUE TITLE
Create a crawler to crawl from Yandex image

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/skin-crawler#17]
Child issue of #4

**Comment by quanggnh** [comment]
There might be problem crawling from Yandex.

**Comment by Huy-Ngo** [comment]
Do you need my help?

**Comment by quanggnh** [comment]
Yes, I couldn't extract the information I need with BeautifulSoup. The class I need just won't show up in soup.findAll

**Comment by Huy-Ngo** [comment]
OK I'll help you when I finish with #19

**Comment by dinhanhx** [comment]
Gentle ping @quanghaopro Remind deadline for backend 22/11/2020 23:59:69
