### ISSUE TITLE
Create a crawler to crawl from Wikimedia

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/skin-crawler#18]
Child issue of #4

**Comment by Huy-Ngo** [comment]
@DDHLong Are you going to continue with this or should I or @dinhanhx take over?

**Comment by dinhanhx** [comment]
Gentle ping @DDHLong Remind deadline for backend 22/11/2020 23:59:69

**Comment by Huy-Ngo** [comment]
Yea, should be hurry up, and I suggest delegating this to someone else if you're not available.

However, we don't have to finish that early. The API is usable now and frontend work can start. These two sources can come later.

**Comment by dinhanhx** [comment]
@Huy-Ngo I and @DDHLong will try to finish today.

**Comment by DDHLong** [comment]
I was preparing for the French final test during the weekend. I will try to finish it soon
