### ISSUE TITLE
Add Yandex and Wikimedia crawler to the static crawler

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/skin-crawler#29]
It seems even for 1 search, the Wikimedia crawler is time taking. I suppose Yandex one would suffer the same problem. Maybe we should crawl them beforehand.

This also let us write code consistently with the other two crawlers.

**Comment by Huy-Ngo** [comment]
@DDHLong @dinhanhx your opinion on this? If you agree I'll resolve this in #27 right away.

**Comment by dinhanhx** [comment]
I agree with you crawling first because the requirements for this project don't say anything about real-time crawling.
