### ISSUE TITLE
Creating modules that crawl images from websites and API

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/skin-crawler#4]
- [X] Kaggle (#2 - Dinh Anh)
- [x] ISIC (#3 - Vuong)
- [x] Yandex (#26 - Quang)
- [x] Wikimedia (#25 - Long)

**Comment by dinhanhx** [comment]
I think I should spend time on cleaning up branch main. So we don't need Google, Reddit,

**Comment by Huy-Ngo** [comment]
We can do that later.
