### ISSUE TITLE
Frontend development

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/skin-crawler#6]
The frontend needs to show images and caption by requesting from the crawler API.

**Comment by Huy-Ngo** [comment]
Each image should display following information:

- image
- caption
- original host site (with link)
- link to where the image is found

User can enlarge an image to see it more clearly by clicking on the image.

The home page shows 10~20 sample images. User can load more images by clicking a button. Images should be loaded without refreshing the page.

Users can also choose to view from one source only.

**Comment by Huy-Ngo** [comment]
Thanks to #19, not you can use the API for testing frontend.

To run:

- install requirements
- in backend, 
  - run `static_crawler.py`
  - after it finishes, run flask:
     - `EXPORT FLASK_APP=app.py`
     - `EXPORT FLASK_ENV=development`
     - `flask run`

For Windows, please use cmd `set` or read [flask doc](https://flask.palletsprojects.com/en/1.1.x/quickstart/)

**Comment by huonglarne** [comment]
yes sir, i will try my best

**Comment by Huy-Ngo** [comment]
We have ~ 7 days before the deadline so please be hurry.

**Comment by Huy-Ngo** [comment]
Please use JS to consume the API. You have to allow CORS in order to use the API btw.
