### ISSUE TITLE
Module ISIC downloaded failed: truncated image

### ISSUE THREAD

**Issue by dinhanhx** [Huy-Ngo/skin-crawler#9]
As of writing, commit aa8165e, branch [isic-pullrequest](https://github.com/Huy-Ngo/skin-crawler/tree/isic-pullrequest), pull request #3, 
when I called `ISIC_getdata(5, 5, False, False)` and `ISIC_getdata()`, no images are downloaded.
CL ouput:
![image](https://user-images.githubusercontent.com/38489776/99634020-6b506000-2a72-11eb-8c6a-998046442d22.png)

Expected output: a list.

**Comment by casker2209** [comment]
Fixed by setting the global variable ImageFile.LOAD_TRUNCATED_IMAGES to True

**Comment by dinhanhx** [comment]
Seriously man. I came back to test your source code at commit 8616e9fb83a2e9b78d2f29ad6c97cafa5b344572 and it doesn't work. Please test your code somewhere else (Virutal Machine, Virtual Enviroment). This will the last time I test your code.

**Comment by dinhanhx** [comment]
@casker2209 I have tested your sourc code in a clean machine - Google Colab. As a result, it still shows the same output.

**Comment by dinhanhx** [comment]
@casker2209 As of writing, at commit 190243b, I have tested your source code in a clean machine - Google Colab. It works now.
